baseURL = "https://elastic-thompson-b58784.netlify.app/"
languageCode = "en-us"
title = "My First Hugo Site"
theme = "hugo-theme-m10c-master"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[params]
[[menu.main]]
name = "About me"
weight = 1
url = "/introduction/"

[[menu.main]]
name = "Blogpost Assessment"
weight = 1
url = "/blogassessment/"

[[menu.main]]
name = "Annotated definitions"
weight = 1
url = "/annotateddefinitions/"

[[menu.main]]
name = "Resource Guides"
weight = 1
url = "/resourceguides/"

[[menu.main]]
name = "Walkthrough"
weight = 1
url = "/walkthrough/"

[[params.social]]
name = "github"
url = "https://github.com/vaga"

[[params.social]]
name ="twitter"
url = "https://twitter.com/vaga"


lightColor = "#f5e3e0"
lightestColor = "#f5f5f5"
primaryColor = "#fff"


